# Generated by Django 5.1.3 on 2025-02-25 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_customuser_is_mod'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_mod',
            field=models.BooleanField(default=False),
        ),
    ]
