# Generated by Django 5.1.3 on 2025-02-27 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_customuser_is_mod'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_mod',
        ),
    ]
