# Generated by Django 5.1.3 on 2025-03-02 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_borrow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrow',
            name='student_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
